### ISSUE TITLE
error building docker

### ISSUE THREAD

**Issue by ephemeraldream** [poppanda/LLM_PDF_Translator#7]
Even straight up docker build gives errors, the app is useless. At least write down the versions of your packages in the req.txt. Half of the packages conflict with each other.

**Comment by Fr4m3** [comment]
me to 
😒

**Comment by hnvcam** [comment]
There are a few places to change in order to make the Docker build work (I did not try to run it locally). For a quick start, you can use the Docker image: `hnvcam/pdf-translator:0.1.0`. The command to run is:
```
docker run -it -v $(pwd)/download:/app/download -v $(pwd)/translate:/app/translate -v $(pwd)/fonts:/app/fonts -v $(pwd)/config.yaml:/app/config.yaml -p 8765:8765 --runtime=nvidia --gpus all --name pdf-translator hnvcam/pdf-translator:0.1.0
```
I mapped those paths to the outside for convenience.
With the default `config.yaml`, you will need to download the Chinese font first. Alternatively, you can use my version as an example:
```
translator:
  type: ollama # openai / ollama / qwen
  api_key: YOUR-KEY-GOES-HERE
  model: 'gemma3:12b'
  # the following args are only for ollama and non multi-thread mode(the multi_thread.enable should be false)
  # restart container before ocr and layout model to avoid high vram usage at local
  restart_container: false 
  container_name: 'ollama' # only for ollama, container name
  ollama_url: 'http://192.168.1.33:11434/v1/'
  # Current LLMTranslateBase use the same model to check if the translation is a correct one which 
  # is incorrect for many cases, so this is to skip that.
  skip_check: true


layout:
  type: 'dit'
  device: 'cuda'

ocr:
  type: 'paddle'
  device: 'cuda'

render:
  #type: 'simple'
  type: 'reportlab'
  font_name: 'Times New Roman'
  font_path: './fonts/TimesNewRoman.ttf'
  # This will be overriden in UI.
  render_mode: TRANSLATION_ONLY # INTERLEAVE # TRANSLATION_ONLY / SIDE_BY_SIDE / INTERLEAVE

# does not work
multi_thread:
  enable: false
  # num_thread: 4

gui:
  database_name: 'pdf_translator_files.db'
  download_folder: 'download'
  translate_folder: 'translate'
```
If you still want to try to build it yourself, then this is what I changed:
```
diff --git a/modules/translate/LLMTranslateBase.py b/modules/translate/LLMTranslateBase.py
index 7cdc9ed..456414b 100755
--- a/modules/translate/LLMTranslateBase.py
+++ b/modules/translate/LLMTranslateBase.py
@@ -105,6 +105,7 @@ class LLMTranslateBase(TranslateBase):
         self.from_lang = None
         self.to_lang = None
         self.check_response = None
+        self.skip_check = cfg["skip_check"]

     @abstractmethod
     def init_client(self, cfg: dict) -> OpenAI:
@@ -174,6 +175,8 @@ class LLMTranslateBase(TranslateBase):
             return False

     def check_translation(self, text, translation):
+        if self.skip_check:
+            return True
         splitted_text = [line for line in text.split("\n") if line != ""]
         splitted_translation = [line for line in translation.split("\n") if line != ""]
         if len(splitted_text) != len(splitted_translation):
diff --git a/modules/translate/ollama_translate.py b/modules/translate/ollama_translate.py
index 621c2b1..f63fe23 100644
--- a/modules/translate/ollama_translate.py
+++ b/modules/translate/ollama_translate.py
@@ -8,7 +8,7 @@ class TranslateOllama(LLMTranslateBase):

     def init_client(self, cfg: dict) -> OpenAI:
         return OpenAI(
-            base_url="http://localhost:11434/v1/",
+            base_url=cfg["ollama_url"],
             # required but ignored
             api_key="ollama",
         )
diff --git a/pyproject.toml b/pyproject.toml
index b9f538d..066f2e2 100755
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -3,7 +3,7 @@ name = "llm-pdf-translator"
 version = "0.1.0"
 description = "Add your description here"
 readme = "README.md"
-requires-python = "~=3.11"
+requires-python = "~=3.11.0"
 dependencies = [
     "gradio>=5.29.1",
     "loguru>=0.7.3",
@@ -21,4 +21,5 @@ dependencies = [
     "torch>=2.7.0",
     "torchvision>=0.22.0",
     "transformers>=4.51.3",
+    "onnxruntime>=1.23.2",
 ]
```
